env_variables:
  SQL_USER: nodejsapp
  SQL_PASSWORD: team2password
  SQL_DATABASE: F17336Gteam2
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: database-project-188722:us-east4:dbp

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: database-project-188722:us-east4:dbp
